const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const SET_USERS = "SET_USERS";
const SET_SELECTED_USER = "SET_SELECTED_USER";
const SET_USER_MESSAGES = "SET_USER_MESSAGES";
const SET_SEND_MESSAGES = "SET_SEND_MESSAGES";
const REMOVE_SELECTED_USER = "REMOVE_SELECTED_USER";

export {
     LOGIN,
     LOGOUT,
     SET_USERS,
     SET_SELECTED_USER,
     SET_USER_MESSAGES,
     SET_SEND_MESSAGES,
     REMOVE_SELECTED_USER,
};
